import type { Metadata } from "next";
import localFont from "@next/font/local";
import "../globals.css";

const agentFB = localFont({ src: "../../public/fonts/agency-fb.ttf" });

export const metadata: Metadata = {
  title: "Tastebite",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={agentFB.className}>{children}</body>
    </html>
  );
}
